config:
  framework: "hardhat" 
  framework_version: "2.6.4" 
  node_version: "18" 
  package_manager: "yarn"

environment:
  ALCHEMY_URL: "https://eth-mainnet.g.alchemy.com/v2/demo"
  INFURA_API_KEY: "1234567890abcdef1234567890abcdef"
  HDWALLET_MNEMONIC: "test test test test test test test test test test test test test"

tasks:
  install-dependencies:
    - yarn install
    - mkdir abis